-- BITEZY SCHEMA MIGRATION: LOGISTICS PILLARS (v12.0)
-- ⚠️ RUN THIS IN SUPABASE SQL EDITOR FIRST

-- 1. RESTAURANTS: ADD LOAD TRACKER
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS current_load INTEGER DEFAULT 0;

-- 2. RIDERS: ADD STATUS & COORDINATES (If missing)
ALTER TABLE riders ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'OFFLINE';
ALTER TABLE riders ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE riders ADD COLUMN IF NOT EXISTS long DOUBLE PRECISION;

-- 3. ORDERS: ADD LOGISTICS TIMESTAMPS
ALTER TABLE orders ADD COLUMN IF NOT EXISTS estimated_arrival_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS prep_started_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS prep_completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS picked_up_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMP WITH TIME ZONE;
